<?php

namespace Leafwrap\ModuleScaffolder;

use Illuminate\Support\ServiceProvider;
use Leafwrap\ModuleScaffolder\Console\Commands\ModuleMake;
use Leafwrap\ModuleScaffolder\Console\Commands\ModuleScaffold;

class ModuleScaffolderServiceProvider extends ServiceProvider
{
    public function boot()
    {
        if ($this->app->runningInConsole()) {
            $this->commands([
                ModuleScaffold::class,
                ModuleMake::class,
            ]);
        }
    }

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }
}
